name: Run Markdown to discord

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: MarkdownToDiscord
        uses: LittleBigRefresh/MarkdownToDiscord@b9cbdf6b9e4bce1bb954d791570fd3e20b29daa7
        with:
          discordToken: ${{ secrets.DISCORD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          markdownDirectory: "markdown"
