name: Run Markdown to discord

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: MarkdownToDiscord
        uses: LittleBigRefresh/MarkdownToDiscord@45eb722d4b6ec756ec919f54668d749df506ffc9
        with:
          discordToken: ${{ secrets.DISCORD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          markdownDirectory: "markdown"
