name: Run Markdown to discord

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: MarkdownToDiscord
        uses: LittleBigRefresh/MarkdownToDiscord@6395f32be090cb3b86390d9e21272adec4fe1434
        with:
          discordToken: ${{ secrets.DISCORD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          markdownDirectory: "markdown"
