name: Run Markdown to discord

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: MarkdownToDiscord
        uses: LittleBigRefresh/MarkdownToDiscord@dbbd7a9
        with:
          discordToken: {{ secrets.DISCORD_TOKEN }}
          markdownDirectory: "markdown"