name: Run Markdown to discord

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: MarkdownToDiscord
        uses: LittleBigRefresh/MarkdownToDiscord@c0f42c2fc0042fb6b40917317e3131db4f3b57ad
        with:
          discordToken: ${{ secrets.DISCORD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          markdownDirectory: "markdown"
